### ISSUE TITLE
Pytest-replay does not generate files on Github Actions

### ISSUE THREAD

**Issue by KelSolaar** [ESSS/pytest-replay#49]
Hello,

I have been trying to use `pytest-replay` as part of pytest-dev/pytest-xdist/issues/979 and I cannot get [any files written on Github Actions](https://github.com/colour-science/colour/actions/runs/7057258055/job/19210607354#step:14:39). The plugin is [loaded correctly afaik](https://github.com/colour-science/colour/actions/runs/7057258055/job/19210607354#step:13:22) and the `poetry run python -W ignore -m pytest --doctest-modules --ignore=$CI_PACKAGE/examples --cov=$CI_PACKAGE $CI_PACKAGE --replay-record-dir=replay` command works fine locally and generate the expected txt files:

![image](https://github.com/ESSS/pytest-replay/assets/99779/a9fca11e-3085-4ba5-b91f-c06dddbd0776)

**Comment by nicoddemus** [comment]
Use `ls -la`, the files start with `.` so they are hidden by default.

**Comment by KelSolaar** [comment]
No worries, and thanks again!
