### ISSUE TITLE
Ignore empty lines in replay files

### ISSUE THREAD

**Issue by DavideCanton** [ESSS/pytest-replay#70]
When cutting/pasting stuff around in the replay files, lines can be commented out, but if some blank line is added, the run errors. I suspect this is because the code always does a `json.loads` if the line is not a comment.

What about skipping empty lines along with commented ones?

**Comment by nicoddemus** [comment]
Sounds reasonable. 👍

**Comment by DavideCanton** [comment]
I can submit a PR in these days

**Comment by nicoddemus** [comment]
`1.5.3` released with this fix, thanks!
